name: openblas-build

on:
  push:
    branches:
      - master
    paths:
      - 'openblas-build/**'
      - '.github/workflows/openblas-build.yml'
  pull_request: 
    paths:
      - 'openblas-build/**'
  workflow_dispatch: {}

jobs:
  linux:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        test_target:
          - build_no_lapacke
          - build_no_shared
          - build_openmp
    container:
      image: rust
    env:
      RUST_BACKTRACE: 1
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Install gfortran by apt
        run: |
          apt update
          apt install -y gfortran
      - name: Common minor tests
        run: cargo test  --manifest-path=openblas-build/Cargo.toml
      - name: Build test
        run: cargo test ${{ matrix.test_target }} --manifest-path=openblas-build/Cargo.toml -- --ignored
