name: Rust

on:
  push:
    branches:
      - master
  pull_request: {}
  workflow_dispatch: {}

jobs:
  check-format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Check format
        run: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - name: Check format
        run: cargo clippy
